export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"

export const SET_MESSAGE = "SET_MESSAGE"
export const CLEAR_MESSAGE = "CLEAR_MESSAGE"

export const SET_FILTER = "SET_FILTER"
export const SET_RESET = "SET_RESET"
export const CLEAR_FILTER = "CLEAR_FILTER"

export const SET_BREADCRUMB = "SET_BREADCRUMB"
export const CLEAR_BREADCRUMB = "CLEAR_BREADCRUMB"
export const DASHBOARDDATA_SUCCESS = "DASHBOARDDATA_SUCCESS"
export const DASHBOARDDATA_FAIL = "DASHBOARDDATA_FAIL"

export const POSITIONLIST_SUCCESS = "POSITIONLIST_SUCCESS"
export const POSITIONLIST_FAIL = "POSITIONLIST_FAIL"

export const SET_TRIAL = "SET_TRIAL"
export const CLEAR_TRIAL = "CLEAR_TRIAL"

export const SET_SAVED_DATA = "SET_SAVED_DATA"
export const CLEAR_SAVED_DATA = "CLEAR_SAVED_DATA"
