export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"

export const SET_MESSAGE = "SET_MESSAGE"
export const CLEAR_MESSAGE = "CLEAR_MESSAGE"

export const SET_MILL = "SET_MILL"
export const SET_MILLS = "SET_MILLS"
export const SET_BU = "SET_BU"

export const SET_BREADCRUMB = "SET_BREADCRUMB"

export const SET_EXPAND_CHART = "SET_EXPAND_CHART"

//PowerDashboard
export const SET_DISPLAY_AS_DATE = "SET_DISPLAY_AS_DATE"
export const SET_LATEST_DATE = "SET_LATEST_DATE"
export const SET_PROCESS_LINE = "SET_PROCESS_LINE"

//Lostcook
export const SET_FIBER_LINE = "SET_FIBER_LINE"
export const SET_LC_ANALYSIS_FILTERED_TABLE = "SET_LC_ANALYSIS_FILTERED_TABLE"
export const SET_LC_ANALYSIS_TABLE = "SET_LC_ANALYSIS_TABLE"
export const SET_SELECTED_DATE_ON_BAR_CHART = "SET_SELECTED_DATE_ON_BAR_CHART"
export const SET_SELECTED_TYPE_ON_PIE_CHART = "SET_SELECTED_TYPE_ON_PIE_CHART"
//Lostcook-Summary-Today
export const SET__SAVE__NEW_PRODUCT_LIST_OF_FIBERLINE =
  "SET__SAVE__NEW_PRODUCT_LIST_OF_FIBERLINE"
export const SET__SAVE__MODIFIED_PRODUCT_LIST_OF_FIBERLINE =
  "SET__SAVE__MODIFIED_PRODUCT_LIST_OF_FIBERLINE"
export const IS_MODIFIED_CONFIG = "IS_MODIFIED_CONFIG"
export const SET_SAVE_MODIFIED_SUMMARY_COOK_LIST =
  "SET_SAVE_MODIFIED_SUMMARY_COOK_LIST"
//CI
export const SET_DISPLAY_PROCESS_LINE = "SET_DISPLAY_PROCESS_LINE"
export const SET_DISPLAY_KPIS = "SET_DISPLAY_KPIS"
export const SET_DISPLAY_PERIODS = "SET_DISPLAY_PERIODS"
